[package]
name = "up_down_game"
version = "0.1.0"
authors = ["r3dzone"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"
